version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'

  dronepollservice:
    build: ./dronepollservice
    restart: always
    environment:
      BACKEND_DRONE_ENDPOINT: http://backend:3001/drone
