version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

  dronepollservice:
    build: ./dronepollservice
    restart: always
    environment:
      BACKEND_DRONE_ENDPOINT: http://backend:3001/drone
